# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: recommendationservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.2
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: DISABLE_PROFILER
          value: "1"
        - name: OPENROUTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: recommendationservice-openrouter
              key: OPENROUTER_API_KEY
        - name: OPENROUTER_TIMEOUT_SECONDS
          valueFrom:
            configMapKeyRef:
              name: llm-config
              key: OPENROUTER_TIMEOUT_SECONDS
        - name: LLM_MODE
          valueFrom:
            configMapKeyRef:
              name: llm-config
              key: LLM_MODE
              optional: true
        - name: OPENROUTER_LOCAL_MODELS
          valueFrom:
            configMapKeyRef:
              name: llm-config
              key: OPENROUTER_LOCAL_MODELS
              optional: true
        # Optional overrides from llm-config-override ConfigMap
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: llm-config-override
              key: TZ
              optional: true
        - name: LLM_ACTIVE_HOURS
          valueFrom:
            configMapKeyRef:
              name: llm-config-override
              key: LLM_ACTIVE_HOURS
              optional: true
        - name: LLM_RATE_LIMIT_PER_MINUTE
          valueFrom:
            configMapKeyRef:
              name: llm-config-override
              key: LLM_RATE_LIMIT_PER_MINUTE
              optional: true
        - name: LLM_SAMPLE_RATE
          valueFrom:
            configMapKeyRef:
              name: llm-config-override
              key: LLM_SAMPLE_RATE
              optional: true
        - name: OPENROUTER_MODEL
          valueFrom:
            configMapKeyRef:
              name: llm-config-override
              key: OPENROUTER_MODEL
              optional: true
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
